Repository codesquad-member-2020/baseball-06, pull requests merged in 2020-05, with the labels that each got.

#10 게임 목록 화면 UI 구현
  iOS/.gitignore
  iOS/BaseBall/BaseBall.xcodeproj/project.pbxproj
  iOS/BaseBall/BaseBall.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/BaseBall/BaseBall.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/BaseBall/BaseBall/AppDelegate.swift
  iOS/BaseBall/BaseBall/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/baseball.imageset/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/baseball.imageset/baseball.jpg
  iOS/BaseBall/BaseBall/Assets.xcassets/first.imageset/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/first.imageset/first.pdf
  iOS/BaseBall/BaseBall/Assets.xcassets/second.imageset/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/second.imageset/second.pdf
  iOS/BaseBall/BaseBall/Base.lproj/LaunchScreen.storyboard
  iOS/BaseBall/BaseBall/Base.lproj/Main.storyboard
  iOS/BaseBall/BaseBall/FirstViewController.swift
  iOS/BaseBall/BaseBall/GameList/GameListBackgroundVIew.swift
  iOS/BaseBall/BaseBall/GameList/GameListViewController.swift
  iOS/BaseBall/BaseBall/GameList/GameStackView.swift
  iOS/BaseBall/BaseBall/GameList/GameTitleView.swift
  iOS/BaseBall/BaseBall/GameList/GameTitleView.xib
  iOS/BaseBall/BaseBall/Info.plist
  iOS/BaseBall/BaseBall/SceneDelegate.swift
  iOS/BaseBall/BaseBall/SecondViewController.swift
Labels: iOS

#13 게임 진행 화면 UI 구현
  iOS/BaseBall/BaseBall.xcodeproj/project.pbxproj
  iOS/BaseBall/BaseBall/Assets.xcassets/play.imageset/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/play.imageset/Icon-76.png
  iOS/BaseBall/BaseBall/Base.lproj/Main.storyboard
  iOS/BaseBall/BaseBall/FirstViewController.swift
  iOS/BaseBall/BaseBall/GameList/GameListViewController.swift
  iOS/BaseBall/BaseBall/GameList/View/GameListBackgroundVIew.swift
  iOS/BaseBall/BaseBall/GameList/View/GameStackView.swift
  iOS/BaseBall/BaseBall/GameList/View/GameTitleView.swift
  iOS/BaseBall/BaseBall/GameList/View/GameTitleView.xib
  iOS/BaseBall/BaseBall/GamePlay/GameProgress/CircleShapeView.swift
  iOS/BaseBall/BaseBall/GamePlay/GameProgress/DiamondShapeView.swift
  iOS/BaseBall/BaseBall/GamePlay/GameProgress/GameProgressView.swift
  iOS/BaseBall/BaseBall/GamePlay/GameProgress/PentagonShapeView.swift
  iOS/BaseBall/BaseBall/GamePlay/GameProgress/PitchButton.swift
  iOS/BaseBall/BaseBall/GamePlay/PitchingResult/CircleNumberLabel.swift
  iOS/BaseBall/BaseBall/GamePlay/PitchingResult/PitchingResultCell.swift
  iOS/BaseBall/BaseBall/GamePlay/PitchingResult/PitchingResultDataSource.swift
  iOS/BaseBall/BaseBall/GamePlay/PlayViewController.swift
  iOS/BaseBall/BaseBall/GamePlay/PlayerInfo/PlayerInfoCell.swift
  iOS/BaseBall/BaseBall/GamePlay/PlayerInfo/PlayerInfoDataSource.swift
  iOS/BaseBall/BaseBall/GamePlay/PlayerInfo/PlayerInfoTableView.swift
Labels: iOS

#7 be/feature/batting
  BE/build.gradle
  BE/src/main/java/com/codesquad/baseball06/Baseball06Application.java
  BE/src/main/java/com/codesquad/baseball06/config/SwaggerConfig.java
  BE/src/main/java/com/codesquad/baseball06/controller/DevController.java
  BE/src/main/java/com/codesquad/baseball06/controller/InningController.java
  BE/src/main/java/com/codesquad/baseball06/model/ApiResponse.java
  BE/src/main/java/com/codesquad/baseball06/model/Batter.java
  BE/src/main/java/com/codesquad/baseball06/model/Inning.java
  BE/src/main/java/com/codesquad/baseball06/model/Pitcher.java
  BE/src/main/java/com/codesquad/baseball06/model/Player.java
  BE/src/main/java/com/codesquad/baseball06/model/Team.java
  BE/src/main/java/com/codesquad/baseball06/model/type/BattingResult.java
  BE/src/main/java/com/codesquad/baseball06/service/InningService.java
  BE/src/main/java/com/codesquad/baseball06/service/PlateAppearanceService.java
  BE/src/main/java/com/codesquad/baseball06/service/PlayerService.java
  BE/src/test/java/com/codesquad/baseball06/model/PlayerTest.java
  BE/src/test/java/com/codesquad/baseball06/service/InningServiceTest.java
  BE/src/test/java/com/codesquad/baseball06/service/PlateAppearanceServiceTest.java
Labels: BE, feature

#19 refactor
  BE/src/main/java/com/codesquad/baseball06/controller/DevController.java
  BE/src/main/java/com/codesquad/baseball06/controller/InningController.java
  BE/src/main/java/com/codesquad/baseball06/message/DevMessage.java
  BE/src/main/java/com/codesquad/baseball06/model/Batter.java
  BE/src/main/java/com/codesquad/baseball06/model/Inning.java
  BE/src/main/java/com/codesquad/baseball06/model/Pitcher.java
  BE/src/main/java/com/codesquad/baseball06/model/Player.java
  BE/src/main/java/com/codesquad/baseball06/model/Team.java
  BE/src/main/java/com/codesquad/baseball06/service/DevService.java
  BE/src/main/java/com/codesquad/baseball06/service/InningService.java
  BE/src/test/java/com/codesquad/baseball06/Baseball06ApplicationTests.java
  BE/src/test/java/com/codesquad/baseball06/service/InningServiceTest.java
  BE/src/test/java/com/codesquad/baseball06/service/PlateAppearanceServiceTest.java
Labels: BE

#29 상세 스코어 화면 UI 구현
  iOS/BaseBall/BaseBall.xcodeproj/project.pbxproj
  iOS/BaseBall/BaseBall/Base.lproj/Main.storyboard
  iOS/BaseBall/BaseBall/Extension/UILabel+bold.swift
  iOS/BaseBall/BaseBall/Score/ScoreCell.swift
  iOS/BaseBall/BaseBall/Score/ScoreDataSource.swift
  iOS/BaseBall/BaseBall/Score/SecondViewController.swift
  iOS/BaseBall/BaseBall/SecondViewController.swift
Labels: iOS

#36 Be/feature/service
  BE/src/main/java/com/codesquad/baseball06/exception/CustomAdvice.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/PlayerDao.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/TeamDao.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/mapper/BatterMapper.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/mapper/BatterReturnDtoMapper.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/mapper/PitcherMapper.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/mapper/PitcherReturnDtoMapper.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/mapper/TeamMapper.java
  BE/src/main/java/com/codesquad/baseball06/model/entity/Player.java
  BE/src/main/java/com/codesquad/baseball06/model/query/Player.java
  BE/src/main/java/com/codesquad/baseball06/model/query/Team.java
  BE/src/main/resources/data.sql
  BE/src/test/java/com/codesquad/baseball06/model/PlayerTest.java
  BE/src/test/java/com/codesquad/baseball06/model/dao/PlayerDaoTest.java
  BE/src/test/java/com/codesquad/baseball06/model/dao/TeamAndPlayerDaoTest.java
  BE/src/test/java/com/codesquad/baseball06/model/dao/TeamDaoTest.java
Labels: BE

#47 Be/feature/inningstart
  BE/src/main/java/com/codesquad/baseball06/controller/GameController.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/GameDao.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/HalfInningDao.java
  BE/src/main/java/com/codesquad/baseball06/model/entity/BaseStatus.java
  BE/src/main/java/com/codesquad/baseball06/model/entity/Game.java
  BE/src/main/java/com/codesquad/baseball06/model/entity/HalfInning.java
  BE/src/main/java/com/codesquad/baseball06/model/entity/InningStatus.java
  BE/src/main/java/com/codesquad/baseball06/model/entity/PlateAppearance.java
  BE/src/main/java/com/codesquad/baseball06/model/query/HalfInningQuery.java
  BE/src/main/java/com/codesquad/baseball06/service/GameService.java
  BE/src/main/java/com/codesquad/baseball06/service/InningService.java
  BE/src/main/java/com/codesquad/baseball06/service/PlateAppearanceService.java
Labels: BE, database, feature

#52 Be/feature/seconddeploy
  BE/src/main/java/com/codesquad/baseball06/controller/GameController.java
  BE/src/main/java/com/codesquad/baseball06/dto/BattingResultDto.java
  BE/src/main/java/com/codesquad/baseball06/dto/BattingResultReturnDto.java
  BE/src/main/java/com/codesquad/baseball06/dto/InningInfoReturnDto.java
  BE/src/main/java/com/codesquad/baseball06/dto/InningStatusDto.java
  BE/src/main/java/com/codesquad/baseball06/dto/UpdatedBasemanDto.java
  BE/src/main/java/com/codesquad/baseball06/dto/UpdatedPlayerDto.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/HalfInningDao.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/InningStatusDao.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/InningStatusDtoReturnDao.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/mapper/PitcherMapper.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/mapper/UpdatedBatterMapper.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/mapper/UpdatedPitcherMapper.java
  BE/src/main/java/com/codesquad/baseball06/model/entity/Batter.java
  BE/src/main/java/com/codesquad/baseball06/model/entity/HalfInning.java
  BE/src/main/java/com/codesquad/baseball06/model/entity/InningStatus.java
  BE/src/main/java/com/codesquad/baseball06/model/entity/Pitcher.java
  BE/src/main/java/com/codesquad/baseball06/model/entity/Player.java
  BE/src/main/java/com/codesquad/baseball06/model/query/HalfInningQuery.java
  BE/src/main/java/com/codesquad/baseball06/model/query/InningStatusQuery.java
  BE/src/main/java/com/codesquad/baseball06/model/query/UpdateInningStatusQuery.java
  BE/src/main/java/com/codesquad/baseball06/service/GameService.java
  BE/src/main/java/com/codesquad/baseball06/service/InningService.java
  BE/src/main/java/com/codesquad/baseball06/service/PlateAppearanceService.java
  BE/src/main/resources/schema.sql
  BE/src/test/java/com/codesquad/baseball06/model/dao/HalfInningDaoTest.java
  BE/src/test/java/com/codesquad/baseball06/model/dao/InningStatusDaoTest.java
  BE/src/test/java/com/codesquad/baseball06/model/dao/inningInfoReturnDtoReturnDaoTest.java
  BE/src/test/java/com/codesquad/baseball06/service/PlateAppearanceServiceTest.java
Labels: BE, feature

#54 Be/feature/bugfix
  BE/src/main/java/com/codesquad/baseball06/config/SimpleCorsFilter.java
  BE/src/main/java/com/codesquad/baseball06/config/WebMvcConfigurerImpl.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/InningStatusDao.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/mapper/GameMapper.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/mapper/HalfInningMapper.java
  BE/src/main/java/com/codesquad/baseball06/model/entity/Game.java
  BE/src/main/java/com/codesquad/baseball06/model/entity/HalfInning.java
  BE/src/main/java/com/codesquad/baseball06/model/query/InningStatusQuery.java
  BE/src/main/java/com/codesquad/baseball06/service/GameService.java
  BE/src/main/java/com/codesquad/baseball06/service/InningService.java
Labels: BE

#60 목업 데이터를 활용한 뷰업데이트
  iOS/BaseBall/BaseBall.xcodeproj/project.pbxproj
  iOS/BaseBall/BaseBall/Base.lproj/Main.storyboard
  iOS/BaseBall/BaseBall/GamePlay/GameProgress/OverallScoreView.swift
  iOS/BaseBall/BaseBall/GamePlay/GameProgress/ScoreStackView.swift
  iOS/BaseBall/BaseBall/GamePlay/PlayViewController.swift
  iOS/BaseBall/BaseBall/GamePlay/PlayerInfo/PlayerInfoCell.swift
  iOS/BaseBall/BaseBall/GamePlay/PlayerInfo/PlayerInfoDataSource.swift
  iOS/BaseBall/BaseBall/GamePlay/ViewModel/InningViewModel.swift
  iOS/BaseBall/BaseBall/GamePlay/ViewModel/ScoreViewModel.swift
  iOS/BaseBall/BaseBall/GamePlay/ViewModel/ViewModelBinding.swift
  iOS/BaseBall/BaseBall/Model/NetworkManager.swift
  iOS/BaseBall/BaseBall/Model/PitchResponse.swift
  iOS/BaseBall/BaseBall/Model/PitchUseCase.swift
Labels: iOS

#63 Be/feature/scoring
  BE/src/main/java/com/codesquad/baseball06/dto/unused/ScoreDto.java
  BE/src/main/java/com/codesquad/baseball06/dto/unused/UpdatedBasemanDto.java
  BE/src/main/java/com/codesquad/baseball06/dto/unused/UpdatedPlayerDto.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/BaseStatusDao.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/GameDao.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/HalfInningDao.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/InningStatusDao.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/InningStatusDtoReturnDao.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/TeamDao.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/mapper/BaseStatusMapper.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/mapper/BasemanStatusMapper.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/mapper/HalfInningMapper.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/mapper/unused/TeamMapper.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/unused/DetailPlateAppearanceDao.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/unused/InningStatusDtoReturnDao.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/unused/PlayerDao.java
  BE/src/main/java/com/codesquad/baseball06/model/entity/BaseStatus.java
  BE/src/main/java/com/codesquad/baseball06/model/entity/HalfInning.java
  BE/src/main/java/com/codesquad/baseball06/model/query/BaseStatusQuery.java
  BE/src/main/java/com/codesquad/baseball06/model/query/HalfInningQuery.java
  BE/src/main/java/com/codesquad/baseball06/model/query/unused/PlayerQuery.java
  BE/src/main/java/com/codesquad/baseball06/service/InningService.java
  BE/src/main/resources/schema.sql
  BE/src/test/java/com/codesquad/baseball06/model/dao/TeamDaoTest.java
  BE/src/test/java/com/codesquad/baseball06/model/dao/inningInfoReturnDtoReturnDaoTest.java
  BE/src/test/java/com/codesquad/baseball06/model/dao/unused/PlayerDaoTest.java
  BE/src/test/java/com/codesquad/baseball06/model/dao/unused/TeamDaoTest.java
  BE/src/test/java/com/codesquad/baseball06/model/dao/unused/inningInfoReturnDtoReturnDaoTest.java
  BE/src/test/java/com/codesquad/baseball06/service/HalfInningServiceTest.java
  BE/src/test/java/com/codesquad/baseball06/service/PlateAppearanceServiceTest.java
  BE/src/test/java/com/codesquad/baseball06/service/unused/PlateAppearanceServiceTest.java
Labels: BE, database, feature

#62 Be/feature/login2
  BE/build.gradle
  BE/src/main/java/com/codesquad/baseball06/config/AuthProperties.java
  BE/src/main/java/com/codesquad/baseball06/config/JwtProperties.java
  BE/src/main/java/com/codesquad/baseball06/controller/AuthController.java
  BE/src/main/java/com/codesquad/baseball06/controller/GameController.java
  BE/src/main/java/com/codesquad/baseball06/message/AuthMessages.java
  BE/src/main/java/com/codesquad/baseball06/message/ErrorMessages.java
  BE/src/main/java/com/codesquad/baseball06/model/entity/Game.java
  BE/src/main/java/com/codesquad/baseball06/service/AuthService.java
  BE/src/main/java/com/codesquad/baseball06/service/GameService.java
  BE/src/main/java/com/codesquad/baseball06/utils/TokenUtil.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/data.sql
  BE/src/main/resources/static/index.html
Labels: BE

#64 Be/refactor
  BE/src/main/java/com/codesquad/baseball06/controller/GameController.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/HalfInningDao.java
  BE/src/main/java/com/codesquad/baseball06/model/entity/HalfInning.java
  BE/src/main/java/com/codesquad/baseball06/model/entity/InningStatus.java
  BE/src/main/java/com/codesquad/baseball06/service/GameService.java
  BE/src/main/java/com/codesquad/baseball06/service/InningService.java
Labels: BE

#66 Be/feature/statusdao
  BE/src/main/java/com/codesquad/baseball06/controller/GameController.java
  BE/src/main/java/com/codesquad/baseball06/dto/InningInfoReturnDto.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/BaseStatusDao.java
  BE/src/main/java/com/codesquad/baseball06/model/query/BaseStatusQuery.java
  BE/src/main/java/com/codesquad/baseball06/service/InningService.java
Labels: BE, database, feature

#67 Be/feature/playerinfo
  BE/src/main/java/com/codesquad/baseball06/controller/GameController.java
  BE/src/main/java/com/codesquad/baseball06/dto/TeamReturnDto.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/TeamDao.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/mapper/EachTeamMapper.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/mapper/PlayerDao.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/mapper/TeamMapper.java
  BE/src/main/java/com/codesquad/baseball06/model/dao/unused/DetailPlateAppearanceDao.java
  BE/src/main/java/com/codesquad/baseball06/model/query/TeamQuery.java
  BE/src/main/java/com/codesquad/baseball06/service/InningService.java
  BE/src/main/resources/schema.sql
  BE/src/test/java/com/codesquad/baseball06/model/dao/PlayerDaoTest.java
  BE/src/test/java/com/codesquad/baseball06/model/dao/unused/TeamDaoTest.java
Labels: BE, database, feature

#74 [BE] fix: 버그 픽스
  BE/src/main/java/com/codesquad/baseball06/model/query/HalfInningQuery.java
  BE/src/main/java/com/codesquad/baseball06/service/GameService.java
  BE/src/main/java/com/codesquad/baseball06/service/InningService.java
Labels: BE
